connect G04_FLIGHT/G04_FLIGHT;
set define off
START E:\script\application\500_create_pqi_param_commun.sql
START E:\script\application\700_create_pqi_db_flight_categ.sql
START E:\script\application\710_create_pqi_db_flight_class.sql
START E:\script\application\720_create_pqi_db_flight_facture.sql
START E:\script\application\730_create_pqi_db_flight_panier.sql
START E:\script\application\740_create_pqi_db_flight_reserv_billet.sql
START E:\script\application\750_create_pqi_db_flight_utilisateur.sql
START E:\script\application\760_create_pqi_db_flight_ville.sql
START E:\script\application\770_create_pqi_db_flight_volreel.sql
START E:\script\application\600_create_pqi_ui_flight_billet.sql
START E:\script\application\620_create_pqi_ui_flight_forrmutilisateur.sql
START E:\script\application\630_create_pqi_ui_flight_home.sql
START E:\script\application\640_create_pqi_ui_flight_menufooter.sql
START E:\script\application\650_create_pqi_ui_flight_panier.sql
START E:\script\application\660_create_pqi_ui_flight_reservation.sql
START E:\script\application\670_create_pqi_ui_flight_utilisateur.sql
START E:\script\application\680_create_pqi_ui_flight_vol.sql
START E:\script\application\500_create_pqb_param_commun.sql
START E:\script\application\700_create_pqb_db_flight_categ.sql
START E:\script\application\710_create_pqb_db_flight_class.sql
START E:\script\application\720_create_pqb_db_flight_facture.sql
START E:\script\application\730_create_pqb_db_flight_panier.sql
START E:\script\application\740_create_pqb_db_flight_reserv_billet.sql
START E:\script\application\750_create_pqb_db_flight_utilisateur.sql
START E:\script\application\760_create_pqb_db_flight_ville.sql
START E:\script\application\770_create_pqb_db_flight_volreel.sql
START E:\script\application\600_create_pqb_ui_flight_billet.sql
START E:\script\application\610_create_pqb_ui_flight_detailvol.sql
START E:\script\application\620_create_pqb_ui_flight_forrmutilisateur.sql
START E:\script\application\630_create_pqb_ui_flight_home.sql
START E:\script\application\640_create_pqb_ui_flight_menufooter.sql
START E:\script\application\650_create_pqb_ui_flight_panier.sql
START E:\script\application\660_create_pqb_ui_flight_reservation.sql
START E:\script\application\670_create_pqb_ui_flight_utilisateur.sql
START E:\script\application\680_create_pqb_ui_flight_vol.sql