-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------


ALTER TABLE UTILISATEUR ADD (
     CONSTRAINT FK_UTILISATEUR_CATEGORIE
          FOREIGN KEY (NUM_CATEG)
               REFERENCES CATEGORIE (NUM_CATEG)) ;

ALTER TABLE BILLET ADD (
     CONSTRAINT FK_BILLET_CLASSE
          FOREIGN KEY (NUM_CLASS)
               REFERENCES CLASSE (NUM_CLASS)) ;

ALTER TABLE BILLET ADD (
     CONSTRAINT FK_BILLET_RESERVATION
          FOREIGN KEY (NUM_RESERV)
               REFERENCES RESERVATION (NUM_RESERV) ON DELETE CASCADE);

ALTER TABLE BILLET ADD (
     CONSTRAINT FK_BILLET_VOL_REEL
          FOREIGN KEY (NUM_VOLCOM, CODE_VOLREEL)
               REFERENCES VOL_REEL (NUM_VOLCOM, CODE_VOLREEL));

ALTER TABLE BILLET ADD (
     CONSTRAINT FK_BILLET_UTILISATEUR
          FOREIGN KEY (NUM_USER)
               REFERENCES UTILISATEUR (NUM_USER) ON DELETE CASCADE);

ALTER TABLE RESERVATION ADD (
     CONSTRAINT FK_RESERVATION_UTILISATEUR
          FOREIGN KEY (NUM_USER)
               REFERENCES UTILISATEUR (NUM_USER) ON DELETE CASCADE);

ALTER TABLE TERMINAL ADD (
     CONSTRAINT FK_TERMINAL_AEROPORT
          FOREIGN KEY (CODE_AERO)
               REFERENCES AEROPORT (CODE_AERO))   ;

ALTER TABLE VOL_COMMERCIAL ADD (
     CONSTRAINT FK_VOL_COMMERCIAL_VILLEARR
          FOREIGN KEY (CP_VILLEARR)
               REFERENCES VILLE (CP_VILLE))   ;

ALTER TABLE VOL_COMMERCIAL ADD (
     CONSTRAINT FK_VOL_COMMERCIAL_VILLEDEP
          FOREIGN KEY (CP_VILLEDEP)
               REFERENCES VILLE (CP_VILLE))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_VOL_COMMERCIAL
          FOREIGN KEY (NUM_VOLCOM)
               REFERENCES VOL_COMMERCIAL (NUM_VOLCOM))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_AVION
          FOREIGN KEY (NUM_AVION)
               REFERENCES AVION (NUM_AVION))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_AEROPORT_DEP
          FOREIGN KEY (CODE_AERO_DEP)
               REFERENCES AEROPORT (CODE_AERO))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_AEROPORT_ARR
          FOREIGN KEY (CODE_AERO_ARR)
               REFERENCES AEROPORT (CODE_AERO))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_TERMINAL_DEP
          FOREIGN KEY (NUM_TERMINAL_DEP,CODE_AERO_DEP)
               REFERENCES TERMINAL (NUM_TERMINAL,CODE_AERO))   ;

ALTER TABLE VOL_REEL ADD (
     CONSTRAINT FK_VOL_REEL_TERMINAL_ARR
          FOREIGN KEY (NUM_TERMINAL_ARR,CODE_AERO_ARR)
               REFERENCES TERMINAL (NUM_TERMINAL,CODE_AERO))   ;

ALTER TABLE AERO_VILLE ADD (
     CONSTRAINT FK_AERO_VILLE_AEROPORT
          FOREIGN KEY (CODE_AERO)
               REFERENCES AEROPORT (CODE_AERO)
                    ON DELETE CASCADE
)   ;

ALTER TABLE AERO_VILLE ADD (
     CONSTRAINT FK_AERO_VILLE_VILLE
          FOREIGN KEY (CP_VILLE)
               REFERENCES VILLE (CP_VILLE)
                    ON DELETE CASCADE
)   ;

ALTER TABLE VOL_RESERV ADD (
     CONSTRAINT FK_VOL_RESERV_RESERVATION
          FOREIGN KEY (NUM_RESERV)
               REFERENCES RESERVATION (NUM_RESERV)
                    ON DELETE CASCADE
) ;

ALTER TABLE VOL_RESERV ADD (
     CONSTRAINT FK_VOL_RESERV_VOL_REEL
          FOREIGN KEY (NUM_VOLCOM, CODE_VOLREEL)
               REFERENCES VOL_REEL (NUM_VOLCOM, CODE_VOLREEL)
                    ON DELETE CASCADE
) ;

ALTER TABLE CLASSE_AVION ADD (
     CONSTRAINT FK_CLASSE_AVION_AVION
          FOREIGN KEY (NUM_AVION)
               REFERENCES AVION (NUM_AVION)
                    ON DELETE CASCADE
) ;

ALTER TABLE CLASSE_AVION ADD (
     CONSTRAINT FK_CLASSE_AVION_CLASSE
          FOREIGN KEY (NUM_CLASS)
               REFERENCES CLASSE (NUM_CLASS)
                    ON DELETE CASCADE
) ;

ALTER TABLE PERSO_VOL ADD (
     CONSTRAINT FK_PERSO_VOL_PERSONNEL
          FOREIGN KEY (CODE_PERSON)
               REFERENCES PERSONNEL (CODE_PERSON)
                    ON DELETE CASCADE
) ;

ALTER TABLE PERSO_VOL ADD (
     CONSTRAINT FK_PERSO_VOL_VOL_REEL
          FOREIGN KEY (NUM_VOLCOM, CODE_VOLREEL)
               REFERENCES VOL_REEL (NUM_VOLCOM, CODE_VOLREEL)
                    ON DELETE CASCADE
)  ;
