ANALYZE TABLE AEROPORT VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE CATEGORIE VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE UTILISATEUR VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE BILLET VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE RESERVATION VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE VILLE VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE PERSONNEL VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE AVION VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE TERMINAL VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE CLASSE VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE VOL_COMMERCIAL VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE VOL_REEL VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE AERO_VILLE VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE VOL_RESERV VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE CLASSE_AVION VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE PERSO_VOL VALIDATE STRUCTURE CASCADE;


