DROP TABLE AEROPORT CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE CASCADE CONSTRAINTS;

DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;

DROP TABLE BILLET CASCADE CONSTRAINTS;

DROP TABLE RESERVATION CASCADE CONSTRAINTS;

DROP TABLE VILLE CASCADE CONSTRAINTS;

DROP TABLE PERSONNEL CASCADE CONSTRAINTS;

DROP TABLE AVION CASCADE CONSTRAINTS;

DROP TABLE TERMINAL CASCADE CONSTRAINTS;

DROP TABLE CLASSE CASCADE CONSTRAINTS;

DROP TABLE VOL_COMMERCIAL CASCADE CONSTRAINTS;

DROP TABLE VOL_REEL CASCADE CONSTRAINTS;

DROP TABLE AERO_VILLE CASCADE CONSTRAINTS;

DROP TABLE VOL_RESERV CASCADE CONSTRAINTS;

DROP TABLE CLASSE_AVION CASCADE CONSTRAINTS;

DROP TABLE PERSO_VOL CASCADE CONSTRAINTS;
