CREATE TABLESPACE BD50_DATA
	DATAFILE 'E:\ORACLE\ORADATA\PROD\BD50_DATA.dbf' SIZE 50M
    AUTOEXTEND ON
  ;

CREATE TABLESPACE BD50_IND
	DATAFILE 'E:\ORACLE\ORADATA\PROD\BD50_IND.dbf' SIZE 50M
    AUTOEXTEND ON
  ;