-- TERMINAL
INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (100000,1,'Terminal rouge');
	
INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (100000,2,'Terminal vert');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (100000,3,'Terminal bleu');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (110000,1,'Terminal blanc');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (110000,2,'Terminal gris');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (110000,3,'Terminal noir');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (120000,1,'Terminal Suisse');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (120000,2,'Terminal France');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (120000,3,'Terminal Allemagne');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (130000,1,'Terminal A');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (130000,2,'Terminal B');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (130000,3,'Terminal C');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (140000,1,'Terminal X');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (140000,2,'Terminal Y');

INSERT INTO TERMINAL (CODE_AERO,NUM_TERMINAL,NOM_TERMINAL) 
	VALUES (140000,3,'Terminal Z');


COMMIT;