--Insertion Classe

INSERT INTO CLASSE (NUM_CLASS,NOM_CLASS,REMISE_CLASS) 
	VALUES (1,'Business class',5);

INSERT INTO CLASSE (NUM_CLASS,NOM_CLASS,REMISE_CLASS) 
	VALUES (2,'Economic class',10);

COMMIT;