-- VILLE

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE)
	VALUES ('75000','Paris','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('13000','Marseille','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('33000','Bordeaux','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('95700','Roissy','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('94390','Orly','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('33700','Mérignac','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('13727','Marignane','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('68304','Saint-Louis','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('68000','Mulhouse','France');

INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('4000','Bâle','Suisse');
	
INSERT INTO VILLE (CP_VILLE,NOM_VILLE,PAYS_VILLE) 
	VALUES ('79098','Fribourg-en-Brisgau','Allemagne');

COMMIT;