INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0001,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0001,2);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0002,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0002,2);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0003,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0003,2);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0004,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0004,2);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0005,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0005,2);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0006,1);

INSERT INTO CLASSE_AVION (NUM_AVION, NUM_CLASS) 
VALUES (0006,2);


COMMIT;