-- ===================================================================================================================
--							INSERTION DES DONNEES
-- ===================================================================================================================

-- UTILISATEUR
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'IDMOUSSI','Mohammed',TO_DATE('01/01/1994','DD/MM/YYYY'),'8','90000','BELFORT','FRANCE','0634129548','somemail@gmail.com','FRANCAISE','IA194734','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'DUPONT','Francois',TO_DATE('01/01/1998','DD/MM/YYYY'),'80','7000','PARIS','FRANCE','0634129548','dupont@gmail.com','FRANCAISE','IA194430','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'GRATOS','Luic',TO_DATE( '01/01/1998','DD/MM/YYYY'),'121','90000','BELFORT','FRANCE','0634129548','gratos@gmail.com','FRANCAISE','IA194782','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'XOXO','Vincent',TO_DATE('01/01/1994','DD/MM/YYYY'),'362','7000','PARIS','FRANCE','0634129548','xoxo@gmail.com','FRANCAISE','IA194322','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (2,'SEFIANI','Yassine',TO_DATE('01/01/2009','DD/MM/YYYY'),'15','5241','KENITRA','MAROC','+212634129548','sefiani@gmail.com','MAROCAINE','MA194754','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'KARKOBI','Zak',TO_DATE('01/01/1988','DD/MM/YYYY'),'23','2000','BESANCON','FRANCE','0634129548','karkobi@gmail.com','FRANCAISE','IA194721','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (2,'CARTIER','Michelle',TO_DATE('01/01/2010','DD/MM/YYYY'),'94','69001','LYON','FRANCE','0634129548','cartier@gmail.com','FRANCAISE','IA192309','C');
INSERT INTO UTILISATEUR (NUM_CATEG,NOM_USER,PRE_USER,DNAISS_USER,NRUE_USER,CP_USER,VILLE_USER,PAYS_USER,TEL_USER,ADMEL_USER,NATIO_PASG,NUMPASS_PASG,TYPE_USER) VALUES (1,'SEMRASSI','Leila',TO_DATE('01/01/1996','DD/MM/YYYY'),'10','68000','MULHOUSE','FRANCE','0634129548','semrassi@gmail.com','FRANCAISE','IA194700','C');

COMMIT;


